package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Table(name = "meetings")
public class Meeting {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "title")
    private String title;

    @Column(name = "description")
    private String description;

    @Column(name = "address")
    private String address;

    @Column(name = "image_path")
    private String imagePath;

    @Column(name = "date")
    private Date date;

    private int reportTopicsCount;

    private int usersCount;

    private int presentUsersCount;

    private List<ReportTopic> reportTopics;

    public Meeting() {
        reportTopics = new ArrayList<>();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public boolean isOutdated() {
        return date == null || new Date().after(date);
    }

    public int getReportTopicsCount() {
        return reportTopicsCount;
    }

    public void setReportTopicsCount(int reportTopicsCount) {
        this.reportTopicsCount = reportTopicsCount;
    }

    public int getUsersCount() {
        return usersCount;
    }

    public void setUsersCount(int usersCount) {
        this.usersCount = usersCount;
    }

    public int getPresentUsersCount() {
        return presentUsersCount;
    }

    public void setPresentUsersCount(int presentUsersCount) {
        this.presentUsersCount = presentUsersCount;
    }

    public List<ReportTopic> getReportTopics() {
        return reportTopics;
    }

    public void setReportTopics(List<ReportTopic> reportTopics) {
        this.reportTopicsCount = reportTopics.size();
        this.reportTopics = reportTopics;
    }

    @Override
    public String toString() {
        return "Meeting{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", imagePath='" + imagePath + '\'' +
                ", date=" + date +
                '}';
    }
}
