package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

@Table(name = "moderator_proposals")
public class ModeratorProposal {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "speaker_id")
    private int speakerId;

    @Column(name = "report_topic_id")
    private int reportTopicId;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(int speakerId) {
        this.speakerId = speakerId;
    }

    public int getReportTopicId() {
        return reportTopicId;
    }

    public void setReportTopicId(int reportTopicId) {
        this.reportTopicId = reportTopicId;
    }
}
