package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

@Table(name = "report_topics_speakers")
public class ReportTopicSpeaker {

    @Column(name = "id", key = true, autoGenerated = true)
    private Integer id;

    @Column(name = "report_topic_id")
    private int reportTopicId;

    @Column(name = "speaker_id")
    private int speakerId;

    private User speaker;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getReportTopicId() {
        return reportTopicId;
    }

    public void setReportTopicId(int reportTopicId) {
        this.reportTopicId = reportTopicId;
    }

    public int getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(int speakerId) {
        this.speakerId = speakerId;
    }

    public User getSpeaker() {
        return speaker;
    }

    public void setSpeaker(User speaker) {
        if (speaker != null) {
            setSpeakerId(speaker.getId());
        }
        this.speaker = speaker;
    }
}
