package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

@Table(name = "report_topics")
public class ReportTopic {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "title")
    private String title;

    @Column(name = "meeting_id")
    private int meetingId;

    private ReportTopicSpeaker reportTopicSpeaker;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getMeetingId() {
        return meetingId;
    }

    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }

    public ReportTopicSpeaker getReportTopicSpeaker() {
        return reportTopicSpeaker;
    }

    public void setReportTopicSpeaker(ReportTopicSpeaker reportTopicSpeaker) {
        if (reportTopicSpeaker != null) {
            reportTopicSpeaker.setReportTopicId(getId());
        }
        this.reportTopicSpeaker = reportTopicSpeaker;
    }
}
