package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

@Table(name = "report_topics")
public class ReportTopic {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "title")
    private String title;

    @Column(name = "meeting_id")
    private int meetingId;

    @Column(name = "speaker_id")
    private Integer speakerId;

    private User speaker;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getMeetingId() {
        return meetingId;
    }

    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }

    public int getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(Integer speakerId) {
        this.speakerId = speakerId;
    }

    public User getSpeaker() {
        return speaker;
    }

    public void setSpeaker(User speaker) {
        setSpeakerId(speaker.getId());
        this.speaker = speaker;
    }
}
