package com.conferences.entity;

import com.conferences.annotation.Column;
import com.conferences.annotation.Table;

@Table(name = "topic_proposals")
public class TopicProposal {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "meeting_id")
    private int meetingId;

    @Column(name = "speaker_id")
    private int speakerId;

    @Column(name = "topic_title")
    private String topicTitle;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getMeetingId() {
        return meetingId;
    }

    public void setMeetingId(int meetingId) {
        this.meetingId = meetingId;
    }

    public int getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(int speakerId) {
        this.speakerId = speakerId;
    }

    public String getTopicTitle() {
        return topicTitle;
    }

    public void setTopicTitle(String topicTitle) {
        this.topicTitle = topicTitle;
    }
}
