package com.conferences.annotation;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface Column {

    String name();
    boolean key() default false;
    boolean autoGenerated() default false;

}
