package custom.entity;

import com.conferences.annotation.Column;

public class NoTableAnnotation {

    @Column(name = "id", key = true, autoGenerated = true)
    private int id;

    @Column(name = "title")
    private String title;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
